version: "2"

services:
 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.4.0
  restart: always
  ports:
   - "30003:30003/udp"
  volumes:
   - "./minetest.conf:/etc/minetest/minetest.conf"
   - "minetest:/var/lib/minetest"
  command: ["/usr/local/bin/minetestserver", "--config", "/etc/minetest/minetest.conf", "--gameid", "mesecons_lab"]
  logging:
   options:
    max-size: 50m

 companion:
  build: companion
  volumes:
   - "minetest:/minetest"
  logging:
   options:
    max-size: 50m

volumes:
  minetest: {}